---
- name: Ensure Elasticsearch key is present
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana repository
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644

- name: Install kibana package
  package:
    name: "kibana"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
...
